name: Publish package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install build
        run: python -m pip install build

      - name: Build package
        run: python -m build

      - name: Store package
        uses: actions/upload-artifact@v5
        with:
          name: python-package-distributions
          path: dist/

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/seqpy_tools

    permissions:
      id-token: write

    steps:
      - name: Download package
        uses: actions/download-artifact@v6
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
